[package]
name = "bork-runner"
version = "1.0.0"
edition = "2021"

[dependencies]
turbo = { version = ">=0.3.8", package = "turbo-genesis-sdk", features = [
"solana",
] }

[lib]
crate-type = ["cdylib"]
