[package]
name = "bork-runner"
version = "1.0.0"
edition = "2021"

[dependencies]
turbo = { version = ">=0.3.8", package = "turbo-genesis-sdk", features = [
"solana",
] }
solana-program = "1.15.2" 
dotenv = "0.15.0"

[lib]
crate-type = ["cdylib"]
